### ISSUE TITLE
[Add-on Request] LibRedirect

### ISSUE THREAD

**Issue by OkyDooky** [CookieJarApps/SmartCookieWeb-Preview#106]
Privacy Redirect was requested (and added) a while back #77 but that add-on has been forked and effectively replaced by the frequently-updated and greatly superior add-on [LibRedirect (Firefox)](https://addons.mozilla.org/en-US/firefox/addon/libredirect/).
I think it works in mobile, even though it doesn't yet have official support for it. But this would be very nice to have.

Thanks for the app! I'm looking forward to seeing the SCW UI features returning. (Side question: when did it change from Biscuit Browser and what's the plan for naming, once it reaches a stable version?)

**Comment by daffydock** [comment]
For what is worth, meanwhile you wait, you can download the XPI from the add-ons page directly and install it, if you wish to not wait. I can vouch that it works, as I use the add-on daily for YT, Reddit and Wiki. 

This is my favorite browse due to how it handles add-on settings.

**Comment by OkyDooky** [comment]
Cool. I'll try that for now. How do I install it here? Going to `about:addons` like the LibRedirect Github page suggests for Firefox doesn't seem to work on this.

**Comment by daffydock** [comment]
You get the XPI directly. 

In this case:
https://addons.mozilla.org/firefox/downloads/file/4013817/libredirect-2.3.0.xpi

If you already have Cookieweb, at least for me, it opens the browser and I install it, done. If not, download the browser and search from there or douple click on it via your file-manager and run it from there. 

As I said it works.

**Comment by OkyDooky** [comment]
Huh. Apparently, the Mozilla add·ons page allows you to sideload them fron there. I didn't have to download it in a separate file. The Settings page of LibRedirect is still formatted for desktop and lags fiercely, but the add-on itself works.
Thanks for suggesting I go for it anyways, while we wait.

**Comment by CookieJarApps** [comment]
> Privacy Redirect was requested (and added) a while back #77 but that add-on has been forked and effectively replaced by the frequently-updated and greatly superior add-on [LibRedirect (Firefox)](https://addons.mozilla.org/en-US/firefox/addon/libredirect/). I think it works in mobile, even though it doesn't yet have official support for it. But this would be very nice to have.
> 
> Thanks for the app! I'm looking forward to seeing the SCW UI features returning. (Side question: when did it change from Biscuit Browser and what's the plan for naming, once it reaches a stable version?)

Thanks for the suggestion! I'll add LibRedirect to the add-on set now.

It changed from Biscuit Browser to avoid confusion with a similarly-named desktop web browser. Currently there aren't any specific plans for the name for the version once it reaches stable status.

**Comment by OkyDooky** [comment]
Thanks! Hopefully, this'll help a lot of people.

Ah, I didn't know there was an existing browser with that name.
Maybe you could open a pinned issue once it gets closer to stable (and has more attention) and have people submit and debate suggestions.

**Comment by OkyDooky** [comment]
This probably should have been closed a while back, with Mozilla making all addons available, now. I'll do that, since this is resolved.
