### ISSUE TITLE
File Selection for file uploads Not working.

### ISSUE THREAD

**Issue by malcolm-dane** [CookieJarApps/SmartCookieWeb-Preview#127]
When using a web form to select a file in storage to upload,send,etc the browser fails to select it regardless of permissions or mime types and the page stops functioning.  Android 13. v 20.1.

**Comment by super963883929** [comment]
me too

**Comment by super963883929** [comment]
How can this be resolved

**Comment by CookieJarApps** [comment]
I think it's linked to changes in Android 13. I'll try and get this fixed in the next update in about a week.

**Comment by super963883929** [comment]
> I think it's linked to changes in Android 13. I'll try and get this fixed in the next update in about a week.

Hi, were you able to solve this issue?

**Comment by super963883929** [comment]
> I think it's linked to changes in Android 13. I'll try and get this fixed in the next update in about a week.

Has this problem been solved now

**Comment by super963883929** [comment]
Unable to upload pictures[http://file.1foo.com/2023/12/19/371ffda6830f57b376bae431be0eea90.mp4](url)

**Comment by super963883929** [comment]
I have solved it and need to add this code in the BaseBrowserFragment



    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        promptsFeature.withFeature { it.onActivityResult(requestCode, data, resultCode) }
    }

    override fun onActivityResult(requestCode: Int, data: Intent?, resultCode: Int): Boolean {
        return listOf(promptsFeature).any { it.onActivityResult(requestCode, data, resultCode) }
    }

I hope you can add it and try it out

**Comment by CookieJarApps** [comment]
Thanks for that, it seems to have fixed the issue. I'll get this out in a new update as soon as possible.
