### ISSUE TITLE
SmartCookieWeb Preview 27.0 on Play Store

### ISSUE THREAD

**Issue by uultimaa7** [CookieJarApps/SmartCookieWeb-Preview#138]
@CookieJarApps & team, I love this browser. Thank you so much for making one so perfect.

I'm just wondering if v27 will appear on the Play Store or be skipped? I can't seem to apply the update via the apk from GitHub since I installed it from the Store.

**Comment by CookieJarApps** [comment]
It's great to hear you like the browser! Yes, unfortunately v27 isn't available on the Play Store as it does not meet Google's requirement of targeting the latest version of Android. The next update should be done very soon which updates the target Android version and fixes some associated issues, and this one will be available on Google Play again.

**Comment by uultimaa7** [comment]
Great, thank you very much
