### ISSUE TITLE
Drop Down Boxes in Extension Overlays Not Working

### ISSUE THREAD

**Issue by uultimaa7** [CookieJarApps/SmartCookieWeb-Preview#139]
I have noticed that drop down boxes in extensions that have settings in an overlay and not a separate site/tab don't work. I tried with a bluetooth mouse as well, in case it was a touch issue.

![IMG_20241027_234843.jpg](https://github.com/user-attachments/assets/37160816-514a-4354-9162-a18033cd5bed)

**Comment by CookieJarApps** [comment]
Thanks for letting me know, this should be fixed in the latest update.
