### ISSUE TITLE
Gecko version/release

### ISSUE THREAD

**Issue by silkevicious** [CookieJarApps/SmartCookieWeb-Preview#31]
Is it wanted this switch between release and nightly?
In app/build.gradle
![screen](https://user-images.githubusercontent.com/41053887/117443331-48d6d400-af38-11eb-852b-bda55fd98bf1.png)

Nice work btw! ;-)

**Comment by CookieJarApps** [comment]
They shouldn't be switched, thanks for letting me know. I think when I was switching the app from just GeckoView to Mozilla Android Components, they must have been mixed up. I'll fix that now.
