### ISSUE TITLE
[Addon Request] Bypass Paywall Clean

### ISSUE THREAD

**Issue by pidus** [CookieJarApps/SmartCookieWeb-Preview#33]
AMO: https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-clean-custom/

Description: Add-on allows users to read articles from websites that implement a paywall.

**Comment by CookieJarApps** [comment]
Thanks for the suggestion, I've now added this add-on (it should appear in the app in ~24 hours, but is visible now from the web store at https://addons.smartcookieweb.com)
