### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by silkevicious** [CookieJarApps/SmartCookieWeb-Preview#38]
Hi again!
I would like to build your app to test it but keeps failing.
I'm using CLI and with `./gradlew assemble` it fails with the error

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processGeckoBetaDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/debian/app_builds/smartcookieweb/app/src/main/res/layout/fragment_home.xml:24: AAPT: error: resource drawable/ic_incognito (aka com.cookiejarapps.android.smartcookieweb:drawable/ic_incognito) not found.

     /home/debian/app_builds/smartcookieweb/app/src/main/res/layout/fragment_tabstray.xml:50: AAPT: error: resource drawable/ic_incognito (aka com.cookiejarapps.android.smartcookieweb:drawable/ic_incognito) not found.

```

I tried run it with --info (if you want i link here the full report) and i found this:
`file or directory '/home/debian/app_builds/smartcookieweb/app/libs', not found`
Uhm any clue? Am I missing something? I'm building it in the same way as all the other apps i have in my fdroid repo...
Thank you again!

**Comment by CookieJarApps** [comment]
Sorry about the issue, I think there might be a file missing in the repo. I'll add the file later today, but for now you can try copying another icon to take the place of the incognito icon as a temporary fix. If you go to /app/src/main/res/drawable/ and copy ic_round_add.xml to a new icon named ic_incognito.xml that should fix the issue with the build for now.

**Comment by silkevicious** [comment]
Thank you! Now it fails with success! :-p
I mean it still say `BUILD FAILED` but it produces the apks.
The error changed now, maybe it can help you:

```
Execution failed for task ':app:compileSystemDebugKotlin'.
> Compilation error. See log for more details
```

Still have to try the apks...will let you know, but for now i'm satisfied the same, thank you!

**Comment by silkevicious** [comment]
I added my builds in my repo, if it pleases you: [https://codeberg.org/silkevicious/apkrepo](https://codeberg.org/silkevicious/apkrepo)
Currently providing GeckoRelease versions, but if i have to provide beta or nightly version let me know.
I usually update it every 1-2 day.

**Comment by CookieJarApps** [comment]
Thanks - that's great. I'll make sure I fix the missing file this afternoon. GeckoRelease should work fine, but navbar hiding when the bar is at the top, and swipe to refresh only currently work with the beta and nightly variants.
