### ISSUE TITLE
Cannot edit and delete bookmarks

### ISSUE THREAD

**Issue by DiAnTTA** [CookieJarApps/SmartCookieWeb-Preview#46]
Please add a feature: **Long-press** a bookmark to **Edit** and **Delete**.

>Application version: `6.0 ( 25 )`
>Gecko View: `89.0-20210505003826`
>Mozilla Android Components: `75.0.11, a93fecbb7`

**Comment by CookieJarApps** [comment]
You can edit bookmarks by pressing on the icon - it's not very clear, sorry. I plan to move the options to an icon on the right of the bookmarks in the next update.
