### ISSUE TITLE
[Feature Request] Clean All Browsing Data

### ISSUE THREAD

**Issue by nullpenguinexception** [CookieJarApps/SmartCookieWeb-Preview#55]
It would be great if we can delete all browsing data like we do in Fennec. Also the new "delete browsing data on quit" option might be great as well.

Edit: There is a workaround to clear browsing data with [addon](https://addons.mozilla.org/en-US/firefox/addon/clear-browsing-data/) for now.

![IMG-20210613-WA0001](https://user-images.githubusercontent.com/83981524/121789137-fe91e400-cbc2-11eb-849a-fe92e8ee4f35.jpg)
![IMG-20210613-WA0000](https://user-images.githubusercontent.com/83981524/121789139-ff2a7a80-cbc2-11eb-863c-3ac9ced994c0.jpg)

**Comment by CookieJarApps** [comment]
Sure, I'll add this to the roadmap now
