### ISSUE TITLE
"Web theme" option doesn't work

### ISSUE THREAD

**Issue by tGstep** [CookieJarApps/SmartCookieWeb-Preview#72]
Galaxy A41, Android 11, i set it to dark but nothing happens on webpages :/

**Comment by CookieJarApps** [comment]
Changing the web theme doesn't mean the change will reflect on websites - it just tells websites and extensions the theme you want to use. E.g. if you set it to dark, sites will be able to see that your device is set to dark mode, but it's up to the site to change the page based on that information (DuckDuckGo is an example of a site that does this). If you want all sites to follow the theme, you'll need an add-on like Dark Reader. If you set the theme in the add-on to 'auto', it will follow what you have set as your web theme in the SCWP settings.

**Comment by tGstep** [comment]
I understand. Dark Reader is slow. I see there are theming engines that are snappy. But you're building a fresh browser btw!
