### ISSUE TITLE
Smartcookieweb Preview cannot be installed on Android 12

### ISSUE THREAD

**Issue by fracklaus** [CookieJarApps/SmartCookieWeb-Preview#83]
Hi, 

since I upgraded my mobile on Android 12, smartcookieweb Preview can no longer be installed. I get an error that the packet cannot be parsed. Can you please fix this?

Thank you.

**Comment by CookieJarApps** [comment]
Sure, I'll look into this issue this weekend. Thanks for reporting the issue.

**Comment by vehosah** [comment]
When weekend exactly? Two years later?

**Comment by CookieJarApps** [comment]
Should be fixed as of v13.
