### ISSUE TITLE
Bookmark import error

### ISSUE THREAD

**Issue by MooShuOrc** [CookieJarApps/SmartCookieWeb-Preview#90]
Version 14 & 15:
When importing bookmarks from Kiwi Browser, it fails with the unhelpful explanation, "Error."
The bookmark file is pretty basic, and identifies itself as "!DOCTYPE NETSCAPE-Bookmark-file-1" which seems like an ancient (and compatible) format. Any chance you could add support?

[As a side note, the browser is really coming along well. Pretty soon it'll be direct competition for the big guys. Good luck!]

**Comment by CookieJarApps** [comment]
Thanks for the feature suggestion! I'll add support for the Kiwi Browser bookmark format for imports in the next update this weekend.

**Comment by DiAn-city** [comment]
Hello @CookieJarApps, does [version 24.0](https://github.com/CookieJarApps/SmartCookieWeb-Preview/releases/tag/24.0) still not support importing bookmarks **.html** ?

**Comment by watson96** [comment]
@MooShuOrc 
Yeah I tried importing the html format bookmarks export file from Firefox PC and it didn't work. Only imports smartpreview export format for now seems

**Comment by CookieJarApps** [comment]
Added in 7f634ba, will be available in the next update this week.
