### ISSUE TITLE
"Copy  Paste  Paste And Go" buttons, do not work. 

### ISSUE THREAD

**Issue by daffydock** [CookieJarApps/SmartCookieWeb-Preview#92]
These buttons do not work on Ver.14 

Clicking on link, where it changes the page, and using Android's own Copy or Paste functions, do work. 
Worked on Ver.13

They also work on Mull browser's implementation. A Fork of FF mobile. Granted it is not the same type of build as Cookieweb Preview. As it does not use Geckoview the way that CWP does.

**Comment by CookieJarApps** [comment]
Thanks for reporting the issue! I've fixed in in commit d51b2c272327b774a12c050ff73543bc153edaa1 - it should work correctly in the next update.

**Comment by daffydock** [comment]
Great. 

Really like the build, by the way. The feature of being able to change add-on settings on the fly due to the popup is such an underestimated feature not found in other FF forks I use. As a power user it saves so much time in workflow. 

Just wanted to say, Thanks. 
Cheers.
